In [3]:
# ============================================================
# STEP 1: Load and Explore Dataset
# ============================================================
print("\nSTEP 1: Loading and Exploring the dataset.....")
import pandas as pd
import numpy as np

# Load Fake and Real news datasets
fake = pd.read_csv("Fake.csv")
real = pd.read_csv("True.csv")

print('\n The Fake and Real csv files are imported')

# Display first few rows
print("\nFirst 3 rows of Fake News dataset: ")
display(fake.head(3))

print("\n First 3 rows of Real News dataset:")
display(real.head(3))

# Add Lables: 1 = Fake, 0 = Real 
fake["label"] = 1
real["label"] = 0

# Combine Datasets
df = pd.concat([fake, real])[["text", "label"]]

# Show dataset distribution
print("\nNumber of Fake vs Real samples:")
print(df["label"].value_counts())
print("\n0 = Real News, 1 = Fake News")

STEP 1: Loading and Exploring the dataset.....

 The Fake and Real csv files are imported

First 3 rows of Fake News dataset:

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"

 First 3 rows of Real News dataset:

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"

Number of Fake vs Real samples:
label
1    23481
0    21417
Name: count, dtype: int64

0 = Real News, 1 = Fake News

In [4]:
# ============================================================
# STEP 2: Text Preprocessing
# ============================================================

print("\nSTEP 2: Converting text to numerical features using TF-IDF.....")

from sklearn.feature_extraction.text import TfidfVectorizer

# TF_IDF Vectorization
vectorizer = TfidfVectorizer(max_features=3000, stop_words="english")
X = vectorizer.fit_transform(df["text"]).toarray()
y = df["label"].values

print("Text Successfully converted into numerical features !")
print("Feature matrix shape:", X.shape)

STEP 2: Converting text to numerical features using TF-IDF.....
Text Successfully converted into numerical features !
Feature matrix shape: (44898, 3000)